#ifndef DBMIGRATIONTOOL_GLOBAL_H
#define DBMIGRATIONTOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBMIGRATIONTOOL_LIBRARY)
#define DBMIGRATIONTOOL_EXPORT Q_DECL_EXPORT
#else
#define DBMIGRATIONTOOL_EXPORT Q_DECL_IMPORT
#endif

#endif // DBMIGRATIONTOOL_GLOBAL_H
